name: Build and release

on:
  push:
    tags:
      - "*"

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1

  releases-matrix:
    name: Release Go Binary
    needs: create-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/amd64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:
          - goarch: "386"
            goos: darwin
    steps:
      - uses: actions/checkout@v2

      - id: get_version
        uses: battila7/get-version-action@v2

      - uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./src"
          binary_name: autopilot
          asset_name: autopilot-${{ matrix.goos }}-${{ matrix.goarch }}
          release_tag: ${{ steps.get_version.outputs.version }}

  docker-build:
    name: Docker build
    needs: releases-matrix
    runs-on: ubuntu-latest

    steps:
      - id: get_version
        uses: battila7/get-version-action@v2

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: efejjota/concourse-autopilot
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ steps.get_version.outputs.version }}
          buildArgs: RELEASE_TAG=${{ steps.get_version.outputs.version }}
